### ISSUE TITLE
Logger should have ability to write to files instead (or with) STDOUT.

### ISSUE THREAD

**Issue by idchlife** [idchlife/kanal#14]
Right now logger outputs only to STDOUT. We should provide ability to choose where (or choose multiple sources IF POSSIBLE with default logger, if not - we skip this feature) to log.

**Comment by notetell** [comment]
Should we specify allowed types of output and log filepath in .env file?

**Comment by idchlife** [comment]
closed in favor of https://github.com/idchlife/kanal/issues/16
