### ISSUE TITLE
Specify log level in logger.

### ISSUE THREAD

**Issue by idchlife** [idchlife/kanal#15]
For example for log level INFO we see everything except DEBUG
For log level DEBUG we see everything.

Consult here to see severity levels: https://ruby-doc.org/stdlib-2.7.6/libdoc/logger/rdoc/Logger/Severity.html

**Comment by notetell** [comment]
Do we set log level in .env file or?

**Comment by idchlife** [comment]
> Do we set log level in .env file or?

Right now there is no existence of any .env file anywhere. Log level should be provided to our logger directly in the code.

**Comment by idchlife** [comment]
closed in favor of https://github.com/idchlife/kanal/issues/16
